import { Inter, Syne } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const syne = Syne({ subsets: ["latin"] });

export const metadata = {
  title: "Tipu Sultan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${syne.className}`}>
        <div className="flex bg-[#EEEEEE]">
          <div className="w-[300px] bg-[#FFFFFF] ml-20 h-[630px] my-12">
            <Header />
          </div>
          <div className=" absolute top-12 h-[630px] right-20 max-w-5xl w-full  bg-[#FFFFFF] overflow-auto p-[50px]">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
